[learn-go-cache] Adding list data structure and lru service
karnadattasai/Cache-Go pull request #2
Opened 2020-08-21 04:57 UTC by karnadattasai

2020-08-23 14:19 UTC, priyanshukm commented on main.go
> +	var c cache.Cache
As discussed please add `_test.go` file for testing instead of doing this in main

2020-08-23 14:19 UTC, priyanshukm commented on service/cache/cache.go
> +var capacity = 3
Please make it `const` instead of `var`. Or maybe if you want each type of Cache to have its own capacity you can also make it part of the corresponding struct. And initialise the value from corresponding `New()`

2020-08-23 14:19 UTC, priyanshukm commented on service/cache/cache.go
> +	Display()
We don't need Display fn is a part of Cache Interface. We should not expose it to the user what we have currently in cache.

2020-08-23 14:19 UTC, priyanshukm commented on service/cache/cache.go
> +// func NewLFUCache() Cache {
Please uncomment these lines here, unless it's causing some build issues.

2020-08-23 14:20 UTC, priyanshukm commented on service/cache/lru.go
> +		c.l.MoveBack(node)
I don't think we have to count Read operation as one of the usage of cache. It's for us to know that if data is in cache or not. So just checking if key is in map will suffice.

2020-08-23 14:20 UTC, priyanshukm commented on service/cache/lru.go
> +	// fmt.Println("hi ", c.l.Len(), key)
Please remove the comment with fmt.Println from here and add relevant comments, maybe describing the code.

2020-08-23 14:26 UTC, priyanshukm commented on service/cache/lru.go
> +	m map[int]*list.Node
Although I think we are over complicating the concept of LRU caching here by having map of `int` and `list Node`.
We could have gone for a `map[int]int` and just a `key-value` pair to store the least recently used pair as the size of list and map always remains equal. But I think it's fine as we are doing this process for leaning.

2020-08-23 14:26 UTC, priyanshukm commented on service/cache/lru.go
> +	l list.List
Please rename `l` and `m` to something more relevant maybe describing it's purpose.

2020-08-23 14:27 UTC, priyanshukm requested changes
Please re-raise the PR with suggested changes

2020-08-24 04:05 UTC, karnadattasai commented on service/cache/cache.go
> +// func NewLFUCache() Cache {
Uncommenting those causing errors as there is no return statement

2020-08-24 04:05 UTC, karnadattasai commented on service/cache/lru.go
> +		c.l.MoveBack(node)
Yeah, So should  I also change the function from Read()  to IsPresent() to be precise for the functionality?

2020-08-24 04:05 UTC, karnadattasai commented on service/cache/lru.go
> +	m map[int]*list.Node
If we just store the least recently used pair, wouldn't it take O(N) to compute next least recently used when we are going to remove the current lru element?

2020-08-25 07:35 UTC, priyanshukm commented on service/cache/lru_test.go
> +			for _, ctxt := range tt.initCacheArgs {
`for _, arg := range tt.initCacheArgs`

2020-08-25 07:35 UTC, priyanshukm commented on service/cache/lru_test.go
> +		callReadOrWrite bool // call Read with key if true else call Write with key and value
I don't think this will be required once `MoveBack` from `Read` is removed

2020-08-25 07:35 UTC, priyanshukm commented on service/cache/lru.go
> +	// if given key is already presesnt update the value and move the node to back of the list as it is the most recently used node
typo in word `present`. Also start the comments with capital.

2020-08-25 07:35 UTC, priyanshukm commented on service/cache/lru.go
> +		c.cacheList.MoveBack(node)
Please remove this MoveBack in Read as discussed.

2020-08-25 07:36 UTC, priyanshukm commented on service/cache/lru_test.go
> +			for _, ctxt := range tt.initCacheArgs {
Same for the the `Read` implementation too

2020-08-25 08:13 UTC, priyanshukm approved these changes

2020-08-25 08:14 UTC, merged